name: Render Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Install Render CLI
      run: |
        curl -o /usr/local/bin/render -L https://render.com/download/render-cli/linux/latest
        chmod +x /usr/local/bin/render

    - name: Deploy to Render
      run: |
        render deploy --file=./render.yaml
      env:
        RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
        RENDER_PASSWORD: ${{ secrets.RENDER_PASSWORD }}
