name: Render Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Deploy to Render
      run: |
        render deploy --file=./render.yaml
      env:
        RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
        RENDER_PASSWORD: ${{ secrets.RENDER_PASSWORD }}
